services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app-network

  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./static/images:/app/static/images
      - .:/app
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - MONGO_URL=mongodb://root:password@mongodb:27017/
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: